# Generated by Django 5.1.3 on 2024-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('donation_date', models.DateField()),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Nyeri', 'Nyeri'), ('Meru', 'Meru'), ('Homabay', 'Homabay'), ('Baringo', 'Baringo'), ('Taita Tavete', 'Taita Taveta'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Siaya', 'Siaya'), ('Kwale', 'Kwale'), ('Samburu', 'Samburu'), ('Turkana', 'Turkana')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blood Donation',
                'verbose_name_plural': 'Blood Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
