# Generated by Django 4.2 on 2024-12-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blooddonation',
            options={},
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/donation_images/'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Nyeri', 'Nyeri'), ('Meru', 'Meru'), ('Homabay', 'Homabay'), ('Baringo', 'Baringo'), ('Taita Taveta', 'Taita Taveta'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Siaya', 'Siaya'), ('Kwale', 'Kwale'), ('Samburu', 'Samburu'), ('Turkana', 'Turkana')], max_length=50),
        ),
    ]
