# Generated by Django 4.2 on 2024-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_remove_blooddonation_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
