# Generated by Django 4.2 on 2024-12-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_remove_blooddonation_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blooddonation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_type',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_images/'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
