# Generated by Django 4.2 on 2024-12-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_remove_blooddonation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='age',
            field=models.IntegerField(default='20'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/donation_images/'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='location',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Nyeri', 'Nyeri'), ('Meru', 'Meru'), ('Homabay', 'Homabay'), ('Baringo', 'Baringo'), ('Taita Taveta', 'Taita Taveta'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Siaya', 'Siaya'), ('Kwale', 'Kwale'), ('Samburu', 'Samburu'), ('Turkana', 'Turkana')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
